version: '3.9'
 
services:
 
  web:
    image: wordpress:latest
    restart: unless-stopped
    depends_on:
      - db
      - mailhog
    links:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: database_user
      WORDPRESS_DB_PASSWORD: database_pass
      WORDPRESS_DB_NAME: database_wp_dev
      WORDPRESS_DEBUG: true
    volumes:
      - ./wordpress:/var/www/html
      - ./docker-config/php-wordpress.ini:/usr/local/etc/php/conf.d/php-wordpress.ini

  db:
    image: mysql:5.6.45
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: database_wp_dev
      MYSQL_USER: database_user
      MYSQL_PASSWORD: database_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=database_user
      - PMA_PASSWORD=database_pass
      - UPLOAD_LIMIT=300M
    ports:
      - 8081:80

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"